export interface ThemeColors {
  bg: string;
  surface: string;
  surfaceRaised: string;
  primary: string;
  primaryPressed: string;
  primarySoft: string;
  textPrimary: string;
  textSecondary: string;
  textOnDark: string;
  textOnAccent: string;
  credit: string;
  debit: string;
  success: string;
  successSoft: string;
  error: string;
  errorSoft: string;
  border: string;
  borderStrong: string;
  overlay: string;
  skeleton: string;
  categorySalaryBg: string;
  categorySalaryFg: string;
  categoryInvoiceBg: string;
  categoryInvoiceFg: string;
  categoryRefundBg: string;
  categoryRefundFg: string;
  categoryBonusBg: string;
  categoryBonusFg: string;
  categoryGenericOutBg: string;
  categoryGenericOutFg: string;
  categoryGenericInBg: string;
  categoryGenericInFg: string;
}

export const lightColors: ThemeColors = {
  bg: '#F7F5F7',
  surface: '#FFFFFF',
  surfaceRaised: '#FFFFFF',
  primary: '#E4166B',
  primaryPressed: '#C21159',
  primarySoft: '#FCE4EE',
  textPrimary: '#161221',
  textSecondary: '#6E6B78',
  textOnDark: '#FFFFFF',
  textOnAccent: '#FFFFFF',
  credit: '#1A8F5A',
  debit: '#161221',
  success: '#1A8F5A',
  successSoft: '#E4F5EC',
  error: '#D62839',
  errorSoft: '#FBE7E9',
  border: '#EAE7EC',
  borderStrong: '#D8D4DC',
  overlay: 'rgba(22,18,33,0.48)',
  skeleton: '#ECE9ED',
  categorySalaryBg: '#FCE4EE',
  categorySalaryFg: '#E4166B',
  categoryInvoiceBg: '#E8EEFB',
  categoryInvoiceFg: '#3860C9',
  categoryRefundBg: '#E4F5EC',
  categoryRefundFg: '#1A8F5A',
  categoryBonusBg: '#FDF3D9',
  categoryBonusFg: '#B8860B',
  categoryGenericOutBg: '#F1EFF3',
  categoryGenericOutFg: '#6E6B78',
  categoryGenericInBg: '#E4F5EC',
  categoryGenericInFg: '#1A8F5A',
};

export const darkColors: ThemeColors = {
  bg: '#121016',
  surface: '#1C1A22',
  surfaceRaised: '#242230',
  primary: '#F0447F',
  primaryPressed: '#D6396C',
  primarySoft: '#3A1926',
  textPrimary: '#F5F3F7',
  textSecondary: '#A6A2B0',
  textOnDark: '#FFFFFF',
  textOnAccent: '#1A0C13',
  credit: '#3CC98A',
  debit: '#F5F3F7',
  success: '#3CC98A',
  successSoft: '#173026',
  error: '#F26A76',
  errorSoft: '#3A1A1D',
  border: '#312E3B',
  borderStrong: '#403C4B',
  overlay: 'rgba(0,0,0,0.64)',
  skeleton: '#26232E',
  categorySalaryBg: '#3A1926',
  categorySalaryFg: '#F0447F',
  categoryInvoiceBg: '#152238',
  categoryInvoiceFg: '#7FA6EE',
  categoryRefundBg: '#173026',
  categoryRefundFg: '#3CC98A',
  categoryBonusBg: '#332508',
  categoryBonusFg: '#E0B84B',
  categoryGenericOutBg: '#242230',
  categoryGenericOutFg: '#A6A2B0',
  categoryGenericInBg: '#173026',
  categoryGenericInFg: '#3CC98A',
};
